import json, datetime

ARCHIVE = 'C:/Trading/research_division/state/research_hypotheses.json'
a = json.load(open(ARCHIVE))

new_ideas = [
    {
        'name': 'Correlation_Collapse_Protector',
        'family': 'risk_overlay',
        'instruments': ['XAUUSD'],
        'timeframes': ['H1', 'H4'],
        'description': 'A risk overlay that monitors rolling correlations between XAUUSD and its three most influential cross-asset peers -- DXY (USD Index), US10Y (10-year Treasury yield), and USDJPY -- and dynamically reduces position size when historical correlation structures break down. When Gold decouples from its normal relationship with the dollar or yields (e.g., gold rallies with a rising dollar, or falls with falling yields), it signals that the fundamental regime has shifted, making risk models unreliable. The overlay caps total exposure at 50% of normal during such regimes and requires a correlation re-convergence signal to reinstate full sizing.',
        'market_behaviour': 'Gold normally exhibits strong negative correlation with DXY (-0.6 to -0.8) and US10Y real yields, and positive correlation with USDJPY in risk-on environments. These relationships are not constant -- they tighten during trend regimes and fray during shock events (rate surprises, geopolitical flashpoints, liquidity crises). When correlations collapse, standard volatility-based risk models (which assume stable relationships) fail catastrophically because portfolio hedges stop working simultaneously. The market enters a regime of higher tail dependency -- all assets move together in unexpected ways -- precisely when risk models need to be most conservative. This overlay anticipates that breakdown rather than reacting after a drawdown.',
        'entry_logic': '1. Compute rolling 30-day Pearson correlation of XAUUSD vs DXY, US10Y yield, and USDJPY on H1 data. 2. Compute the 90-day standard deviation of each correlation (the volatility of correlation). 3. Calculate a Correlation Stability Score (CSS) = 1 - (sum of z-scores of the three correlations deviation from their 90-day mean) / 3. 4. Normal range (full exposure): CSS > -1.0. 5. Caution zone (50% exposure): CSS between -1.0 and -2.0. 6. Lockdown zone (25% exposure or no new entries): CSS < -2.0. 7. Recovery: Full sizing resumes only when CSS returns above -0.5 for 3 consecutive days (hysteresis band). Overlay applies at portfolio level, not per-trade.',
        'exit_logic': 'No per-trade exit -- this is a portfolio-level risk overlay. When CSS enters caution zone, any open positions have their trailing stops tightened to 0.5x normal ATR. When CSS enters lockdown zone, all open positions are reduced by 50% (partial close) and no new entries permitted. Recovery to normal sizing triggers position re-entry only if original entry signal is still valid. Hard override: if any single asset shows a 10-day correlation flip (e.g., DXY correlation from -0.7 to +0.3), immediately enter lockdown regardless of CSS score.',
        'failure_mode': 'Fails during structurally persistent regime shifts where a new normal correlation takes hold (e.g., the 2022 gold-DXY regime where both rallied together for months) -- the overlay would remain in lockdown indefinitely, starving the portfolio of exposure during a profitable regime. The 90-day lookback window causes slow adaptation. Correlations are fragile estimators: 30-day Pearson can be distorted by a single outlier day. Also fails in zero-correlation environments where the CSS is persistently in caution zone due to noise, not real regime change.',
        'diversification_value': 'The only overlay in the archive that monitors correlation stability rather than volatility. While Volatility_Parity_Scale adjusts to volatility level, this adjusts to correlation regime -- they are orthogonal risk dimensions. Fills a critical gap: prevents the portfolio from being overexposed precisely when diversification fails (the moment you need protection most). Cannot be replicated by any existing strategy since no current bot monitors cross-asset correlation structures at the portfolio level.',
        'self_grade': 'A-',
        'generated_at': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    },
    {
        'name': 'Event_Window_Seasonal_Compression',
        'family': 'seasonal',
        'instruments': ['XAUUSD'],
        'timeframes': ['D1', 'H4'],
        'description': 'Combines seasonal patterns with macro event windows (FOMC, NFP, CPI, ECB, BOJ rate decisions) to exploit the tendency of Gold to compress its seasonal drift into a narrower window around high-impact events. Rather than holding a seasonal position for weeks, this strategy enters 12 hours before a macro event during seasonally favorable months and exits 24 hours after -- capturing the bulk of seasonal movement while avoiding the noise of non-event days. The hypothesis is that large institutional seasonal flows (hedging, central bank rebalancing, physical settlement) are accelerated through event-driven liquidity pools.',
        'market_behaviour': 'Gold seasonal patterns (Indian wedding demand Oct-Dec, Chinese New Year Jan-Feb, summer lull May-Jul) are well-documented but diffuse -- the total return over a seasonal window is small (1-3%) spread over weeks. However, macro events create liquidity concentration: large orders that would normally dribble in over days are compressed into the hours around FOMC/NFP when depth is highest. The seasonal signal is strongest not on random Tuesdays in November, but in the 36-hour window around high-impact macro events during seasonally favorable periods. The drift provides the directional bias, the event provides the catalyst.',
        'entry_logic': '1. Maintain seasonal calendar: Long-favorable windows (Aug 1 - Sep 15, Oct 15 - Feb 15), Short-favorable windows (Mar 1 - May 1, Jun 15 - Jul 15). 2. Cross-reference with macro event calendar: FOMC (8/year), NFP (12/year), CPI (12/year), ECB rate (8/year), BOJ rate (8/year). 3. Entry condition: A macro event must fall within a seasonally favorable window. 4. Entry timing: 12 hours before the event (e.g., entry Tue 08:00 ET for FOMC Wed 14:00 ET). Direction = seasonal window direction. 5. Position size = 1.5x normal (compressed timeframe justifies higher conviction). 6. Skip if: the event is within 5 days of another same-type event (cluster risk), or if the seasonal window has less than 5 days remaining (insufficient runway).',
        'exit_logic': 'Primary exit: 24 hours after the event release (captures the post-event continuation drift). Time-stop: exit at Friday 17:00 ET regardless. Hard stop: if the event triggers a >2% daily move against position, exit immediately (event-driven trend rejection). SL: 1.5x ATR(14) on H4 from entry. No TP -- exit is purely time-based. If the same seasonal window contains multiple events, treat each independently: exit position A before entering position B.',
        'failure_mode': 'Fails when macro events override seasonal patterns entirely (e.g., a hawkish FOMC surprise during the Nov-Feb seasonal rally, or an emergency rate cut during the Apr short window). Event outcomes are binary and fat-tailed -- a single NFP miss can undo months of seasonal drift. Low trade count (only 15-20 events per year fall in seasonal windows). Backtesting requires 10+ years of event timestamps and exact timestamp entry (not OHLC only). Seasonality itself can break in structurally new macro regimes (COVID, 2008).',
        'diversification_value': 'None of the 5 existing seasonal strategies use macro event windows as the execution catalyst -- they all hold through full calendar windows. This is the first hybrid seasonal+event strategy in the archive. It operates on a fundamentally different timescale (36-hour holds vs. multi-week holds) making it uncorrelated with Gold_Seasonal_Cycle or Turn_Of_Month_Gold. It bridges the gap between seasonal and regime_filter families, a combinatorial space the archive has never explored.',
        'self_grade': 'B+',
        'generated_at': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    },
    {
        'name': 'Structural_Break_Momentum_Flux',
        'family': 'other',
        'instruments': ['XAUUSD'],
        'timeframes': ['H4', 'D1'],
        'description': 'Detects structural market breaks using a novel Momentum Flux Index -- the cumulative divergence between price rate-of-change and volume-weighted velocity -- then trades the re-convergence pattern. Unlike standard momentum (which buys strength) or mean-reversion (which fades extremes), this strategy identifies moments when momentum has exhausted its statistical energy but price has not yet reversed, creating a high-probability zone where the direction is about to change. It sits in the uncorrelated middle ground between momentum and mean-reversion -- it neither chases trends nor fades them, but catches the exact inflection.',
        'market_behaviour': 'Markets transition through distinct phases: accumulation (low energy building), trend (high energy directional), climax (peak energy + exhaustion), and reversion (energy dissipating). Standard momentum strategies buy during trend and fail at climax; mean-reversion strategies buy at climax and succeed at reversion. But both miss the critical edge: the moment between climax and the first bar of reversion. During this flux state, price is range-bound but compressed volatility is about to expand in the opposite direction. Momentum flux (rate of change of momentum, akin to second derivative of price) peaks 1-3 bars before price reverses, providing a leading indicator that neither momentum nor reversion alone can see.',
        'entry_logic': '1. Compute Momentum Flux Index (MFI): apply a rolling linear regression slope to ATR(14) over 20 bars, then divide by the standard deviation of slope (z-score of ATR acceleration). 2. Compute Price Velocity Divergence (PVD): the angle difference between price ROC(14) and a weighted mid-price (H+L/2) ROC(14). 3. Entry conditions for LONG: (a) MFI z-score > +2.5 AND (b) PVD > +1.5 AND (c) price closed in bottom 30% of the last 5 bars AND (d) RSI(14) > 70. 4. Entry conditions for SHORT: inverse -- MFI z-score < -2.5, PVD < -1.5, price in top 30% of 5 bars, RSI < 30. 5. Entry at next H4 open after all conditions met.',
        'exit_logic': 'SL: 1.0x ATR(14) on H4 from entry (tight because entry is at the peak of acceleration -- if wrong, price is still accelerating, so a small stop is essential). TP1: 50% at 1x ATR(14) on H4 (scalp the initial reversion). TP2: 30% at 2x ATR(14) on H4 (reversion continuation). Remainder: trail at 0.5x ATR(14) when price reaches 1x ATR profit. Max hold: 5 days. The tight 1x ATR stop is non-negotiable -- this strategy lives and dies on catching the exact inflection, and wrong entries must be cut ruthlessly.',
        'failure_mode': 'The tight 1x ATR SL causes high strike-rate on non-climax bars (false positives where momentum briefly shows flux but resumes). In strong, uninterrupted trends (e.g., war breakout, rate-cut cycle), the flux signal can fire multiple times and get stopped out each time -- bleeding small losses. Requires tick-level or intra-bar data to compute precise mid-price and acceleration -- standard H4 OHLC may lose signal fidelity. The z-score approach makes it regime-dependent: after a quiet period, even moderate momentum looks extreme.',
        'diversification_value': 'Conceptually novel -- not momentum, not mean-reversion, but a pure inflection-capture strategy that exploits the second derivative of price. No existing idea in any family uses acceleration z-scores or mid-price velocity divergence. This occupies a unique niche: it would fire at exactly the worst possible entry for both momentum bots (which buy climax) and mean-reversion bots (which require clear reversal bars first). It captures edges that both other families miss because they look at different features (level vs. reversal vs. acceleration). Fills a genuine algorithmic gap.',
        'self_grade': 'B',
        'generated_at': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
    }
]

for idea in new_ideas:
    if not any(i['name'] == idea['name'] for i in a['ideas']):
        a['ideas'].append(idea)
        a['coverage_map'].setdefault(idea['family'], []).append(idea['name'])

a['metadata']['total_ideas'] = len(a['ideas'])
a['metadata']['families_covered'] = sorted(set(f for f,v in a['coverage_map'].items() if v))
json.dump(a, open(ARCHIVE, 'w'), indent=2)
print(f'SAVED. Total ideas: {a["metadata"]["total_ideas"]}')
print(f'Families covered: {a["metadata"]["families_covered"]}')
print(f'Coverage counts: {json.dumps({k:len(v) for k,v in a["coverage_map"].items()}, indent=2)}')
